## src/SecondSessionStudent/BUILD

cc_library(
    name = "SecondSessionStudent",
    srcs = ["SecondSessionStudent.cpp"],
    hdrs = ["SecondSessionStudent.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/FirstSessionStudent:FirstSessionStudent",
    ],
)
