## src/FirstSessionStudent/BUILD

cc_library(
    name = "FirstSessionStudent",
    srcs = ["FirstSessionStudent.cpp"],
    hdrs = ["FirstSessionStudent.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Student:Student",
    ],
)
