## src/tests/StringTests/BUILD

cc_library(
    name = "StringTests",
    srcs = ["StringTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/String:String",
    ]
)
