## src/TreesContainer/BUILD

cc_library(
    name = "TreesContainer",
    srcs = ["TreesContainer.cpp"],
    hdrs = ["TreesContainer.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/ForestTree:ForestTree",
        "//src/FruitTree:FruitTree",
    ]
)
