## src/Student/BUILD

cc_library(
    name = "Student",
    srcs = ["Student.cpp"],
    hdrs = ["Student.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Person:Person",
    ],
)
