## src/ForestTree/BUILD

cc_library(
    name = "ForestTree",
    srcs = ["ForestTree.cpp"],
    hdrs = ["ForestTree.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Tree:Tree",
    ],
)
