## src/tests/EmployeeTests/BUILD

cc_library(
    name = "EmployeeTests",
    srcs = ["EmployeeTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Employee:Employee",
    ]
)
