## src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/tests/NumbersTests:NumbersTests",
        "//src/tests/SurnamesTests:SurnamesTests",
        "//src/tests/EmployeeTests:EmployeeTests",
    ],
)
