## src/FruitTree/BUILD

cc_library(
    name = "FruitTree",
    srcs = ["FruitTree.cpp"],
    hdrs = ["FruitTree.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Tree:Tree",
    ],
)
