## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    data = ["//src/Resources:files"],
    deps = [
        "//src/Tree:Tree",
        "//src/ForestTree:ForestTree",
        "//src/FruitTree:FruitTree",
        "//src/TreesContainer:TreesContainer",
    ],
)
