## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        
        "//src/Tree:Tree",
        "//src/ForestTree:ForestTree",
        "//src/FruitTree:FruitTree",
    ],
)
