## src/tests/MatrixTests/BUILD

cc_library(
    name = "MatrixTests",
    srcs = ["MatrixTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Matrix:Matrix",
    ]
)
